name: 'Timmatt-Lee/Github-Jira-Integration'
description: 'Automatically create or bind pull request to jira issue, resolve it when merged'
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  host:
    description: Domain of your jira host
    required: true
  email:
    description: Your jira email address
    required: true
  token:
    description: Your jira access token
    required: true
  project:
    description: Project Short Name
    required: true
  transition:
    description: Transition name that issue take
    required: true
  githubToken:
    description: Your github token
    required: false
  version:
    description: Version Prefix that new issue attach to 
    required: false
  component:
    description: Components that new issue attach to 
    required: false
  type:
    description: New issue type
    required: false
  board:
    description: Sprint query that new issue need to
    required: false
  isOnlyTransition:
    description: Only process transition to Jira issue
    required: false
    default: false
  isCreateIssue:
    description: auto create issue
    required: false
    default: true
  otherAssignedTransition:
    description: if issue is assigned by others, transit to this transition
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
  # using: 'docker'
  # image: 'Dockerfile'
