name: 'Timmatt-Lee/GitHub-Jira-Integration'
description: 'Automatically create or bind pull request to jira issue, resolve it when merged'
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  host:
    description: Domain of your jira host
    required: true
  githubToken:
    description: Your github token
    required: true
  webhook:
    description: Jira webhook trigger
    required: false
  email:
    description: Your jira email address
    required: false
  token:
    description: Your jira access token
    required: false
  project:
    description: Project Short Name
    required: false
  transition:
    description: Transition name that issue take
    required: false
  version:
    description: Version Prefix that new issue attach to 
    required: false
  component:
    description: Components that new issue attach to 
    required: false
  type:
    description: New issue type
    required: false
  board:
    description: Sprint query that new issue need to
    required: false
  isOnlyTransition:
    description: Only process transition to Jira issue
    required: false
    default: 'false'
  isCreateIssue:
    description: Auto create issue
    required: false
    default: 'false'
  otherAssignedTransition:
    description: If issue is assigned by others, transit to this transition
    required: false
  isAssignToReporter:
    description: If you want to re-assign the issue to reporter
    required: false
    default: 'false'
  isOnlyAppendDesc:
    description: true if you only want to update PR description
    required: false
    default: 'false'
  appendDescAfterRegex:
    description: insert jira issue link after this regex of PR description
    required: false
  isAddFixVersionOnMerge:
    description: true if you want to add fix version on merge
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
  # using: 'docker'
  # image: 'Dockerfile'
