on:
  push

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Integration
      uses: ./
      with:
        host: ${{ secrets.JIRA_BASE_URL }}
        email: ${{ secrets.JIRA_USER_EMAIL }}
        token: ${{ secrets.JIRA_API_TOKEN }}
        project: ${{ secrets.JIRA_PROJECT_NAME }}
        version: ${{ secrets.JIRA_VERSION_PREFIX }}
        component: ${{ secrets.JIRA_COMPONENT_NAME }}
        type: ${{ secrets.JIRA_ISSUE_TYPE }}
        board: ${{ secrets.JIRA_BOARD_ID }}
