on:
  pull_request:
    types: [opened]
    branches:
      - master

name: Test Pull Request

jobs:
  test:
    name: Test Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Integration
      uses: ./
      with:
        host: ${{ secrets.JIRA_BASE_URL }}
        email: ${{ secrets.JIRA_USER_EMAIL }}
        token: ${{ secrets.JIRA_API_TOKEN }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        project: ${{ secrets.JIRA_PROJECT_NAME }}
        version: ${{ secrets.JIRA_VERSION_PREFIX }}
        component: ${{ secrets.JIRA_COMPONENT_NAME }}
        type: ${{ secrets.JIRA_ISSUE_TYPE }}
        board: ${{ secrets.JIRA_BOARD_ID }}
        transition: ${{ secrets.JIRA_PR_TRANSITION_NAME }}
        isNotCreateIssue: false
