on:
  pull_request:
    types: [reopened]

name: Test Pull Request

jobs:
  test:
    name: Test Pull Request
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Integration
      uses: ./
      with:
        host: ${{ secrets.JIRA_BASE_URL }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        webhook: ${{ secrets.JIRA_WEBHOOK }}
        token: ${{ secrets.JIRA_API_TOKEN }}
        email: ${{ secrets.JIRA_USER_EMAIL }}
        version: ${{ secrets.JIRA_VERSION_PREFIX }}
        project: ${{ secrets.JIRA_PROJECT_NAME }}
        isAddFixVersionOnMerge: true
