on:
  pull_request:
    types: [opened, closed]
    branches:
      - master

name: Jira Webhook Integration

jobs:
  test:
    name: Jira Webhook Integration
    runs-on: ubuntu-latest
    - name: Integration
      uses: ./
      with:
        host: ${{ secrets.JIRA_BASE_URL }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        webhook: ${{ secrets.JIRA_WEBHOOK }}

