on:
  pull_request:
    branches:
      - master

name: Test Webhook

jobs:
  test:
    name: Test Webhook
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Integration
      uses: ./
      with:
        webhook: ${{ secrets.JIRA_WEBHOOK }}

